# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc2388866e53280d7796a1db77455b4f7a2c0c1b2e755110b1a3fa5657948e8eb0c4a202ef0695f084fa41af8b312b829ec07bf5694fc209bd91279dfffd9877

test:
  secret_key_base: bf0da633af7ffddce17e9e88e13143d03be1f8ec6561b45f258fc1c9ccf6e8491e529aff3d9003c209422e784c95864f04b801a0d04728ac6e6738b2ddc96d8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
